name: protocol_interface
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.5.4
resolution: workspace

dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.24.0
