name: protocol
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.3
resolution: workspace

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  # path: ^1.8.0

  protocol_interface:
    path: ../protocol_interface
  
  mouse_protocol:
    path: ../mouse_protocol
    
  keyboard_protocol:
    path: ../keyboard_protocol


dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.24.0
