name: On Assignment Move to In Progress

on:
  issues:
    types:
      - assigned
  pull_request:
    types:
      - assigned

jobs:
  call-move-workflow:
    uses: ./.github/workflows/move-to-in-progress.yml # Calls the reusable workflow
    with:
      project-url: 'https://github.com/users/cl0v/projects/3' # Replace with your Project URL
      column-name: 'In Progress'
      token: ${{ secrets.GITHUB_TOKEN }}