name: server
description: "Desktop HUB for Celmouse App"
publish_to: "none"
version: 2.0.4+4

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  mouse:
    path: ../plugins/mouse/mouse

  keyboard:
    path: ../plugins/keyboard/keyboard

  protocol:
    path: ../packages/protocol/protocol

  url_launcher: ^6.3.1
  qr_flutter: ^4.1.0
  desktop_window: ^0.4.2
  icons_launcher: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

icons_launcher:
  image_path: "assets/dark_logo.png"
  platforms:
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true
