name: server
description: "Desktop HUB for Celmouse App"
publish_to: "none"
version: 2.2.0+7

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  qr_flutter: ^4.1.0
  desktop_window: ^0.4.2
  icons_launcher: ^3.0.0
  device_info_plus: ^11.2.1
  result_dart: ^2.0.0
  flutter_screenutil: ^5.9.3
  protocol:
    path: ../packages/protocol
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.9.3
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  assets:
    - assets/

icons_launcher:
  image_path: "assets/dark_logo.png"
  platforms:
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true
